version: '3.8'
services:
    postgres:
        image: postgres
        restart: always
        env_file:
            - .env
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - store_network

volumes:
    postgres_data:

networks:
    store_network:
